- name: Playbook-task
    hosts: nodes
    become: yes
    become_user: root
    tasks:
      - name: update
        apt:
        update_cache: yes 
      - name: install docker 
        apt:
          name: docker.io
          state: present
      - name: install openjdk
        apt:
          name: default-jdk-headless 
          state: present
      - name: copy directory
        copy:
          src: agent.jar
          dest: /home/ubuntu
